### ISSUE TITLE
Composition field mappings, where should they go

### ISSUE THREAD

**Issue by SevKohler** [SevKohler/FHIRconnect-spec#6]
```YAML

  - name: "partyIdentifiedComposer"
    with:
      fhir: "$resourcePath.recorder"
      openehr: "$composition/composer" # often required therefore simplified mapping engine is to resolve Reference -> Composer

  - name: "asserter"
    with:
      fhir: "$resourcePath.asserter"
      openehr: "$composition/context/participations"  # often required therefore simplified mapping engine is to resolve Reference -> Participations
    participationsFunction: "asserter" # participations_mode this one has to be done in the mapping and cannot be mapped automatically.

```

The fields are in the archetype (problem_diagnose) in the end but they address elements of the composition, at the composition level. 
Either we leave them in the models, since you have to map that each time. 
Or we put them into the Template-to-profile mappings since they address something on the composition level and there could be several archetypes with this fields which could make the mapping execution for this fields chaotic to debug. 
Imagine two problem diagnoses which composer do you take ?!
